## Python Basics

### Question 1 (5 points)
**Write a Python program to calculate the number of days between two dates.**
Sample dates : (2022, 12, 1), (2022, 12, 19)
Expected output : 18


In [ ]:
from datetime import date
f_date = date(2022, 12, 1)
l_date = date(2022, 12, 19)
delta = l_date - f_date
print(delta.days)

18


### Question 2 (5 points)
**Write a Python program of name diff to calculate the difference between a given number and 61. If the number is greater than 61, return twice the absolute difference.**  

In [ ]:
def diff(n):
    if n <= 61:
        return 61 - n
    else:
        return (n - 61) * 2 

print(diff(22))
print(diff(14))
    
    

39
47


### Question 3 (5 points)
**Write a Python program to get a newly-generated string from a given string where "Ml" has been added to the front. Return the string unchanged if the given string already begins with "ML".**

In [ ]:
def new_string(text):
  if len(text) >= 2 and text [:2] == "ML":
    return text
  return "ML" + text
print(new_string("Array"))
print(new_string("IsEmpty")) 

MLArray
MLIsEmpty


### Question 4 (5 points)
**Write a Python program that returns a string that is n (non-negative integer) copies of a given string.**

In [ ]:
def larger_string(text, n):
   result = ""
   for i in range(n):
      result = result + text
   return result
print(larger_string('abc', 2))
print(larger_string('.py', 3)) 

abcabc
.py.py.py


# NumPy Basics

In [ ]:
import numpy as np

### Question 4 (5 points)
**Write a NumPy program to find the number of rows and columns of a given matrix**

In [ ]:
import numpy as np
m= np.arange(10,22).reshape((3, 4))
print("Original matrix:")
print(m)
print("Number of rows and columns of the said matrix:")
print(m.shape)

Original matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Number of rows and columns of the said matrix:
(3, 4)


### Question 5 (5 points)
**Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.**

In [ ]:
import numpy as np
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Question 6 (5 points)
**Write a NumPy program to compute the inner product of two given vectors.**

In [ ]:
import numpy as np
x = np.array([4, 5])
y = np.array([7, 10])
print("Original vectors:")
print(x)
print(y)
print("Inner product of said vectors:")
print(np.dot(x, y))


Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


### Question 7 (5 points)
**Complete the function `inverse` that computes the inverse of a matrix.**

In [ ]:
import numpy as np 

x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x)
print (y) 
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


### Question 8 (10 points)
**Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.**

In [ ]:
import numpy as np
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
n = 8.32
r = 18.32
print("\nReplace elements of the said array which are equal to ",n,"with",r)
print(np.where(nums == n, r, nums))
print("\nReplace elements with of the said array which are less than",n,"with",r)
print(np.where(nums < n, r, nums))
print("\nReplace elements with of the said array which are greater than",n,"with",r)
print(np.where(nums > n, r, nums))

Original array:
[[5.54 3.38 7.99]
 [3.54 8.32 6.99]
 [1.54 2.39 9.29]]

Replace elements of the said array which are equal to  8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54 18.32  6.99]
 [ 1.54  2.39  9.29]]

Replace elements with of the said array which are less than 8.32 with 18.32
[[18.32 18.32 18.32]
 [18.32  8.32 18.32]
 [18.32 18.32  9.29]]

Replace elements with of the said array which are greater than 8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54  8.32  6.99]
 [ 1.54  2.39 18.32]]


### Question 9 (10 points)
**Write a NumPy program to swap rows and columns of a given array in reverse order.**

In [ ]:
import numpy as np
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
print("Original array:")
print(nums)
print("\nSwap rows and columns of the said array in reverse order:")
new_nums = print(nums[::-1, ::-1])
print(new_nums)

Original array:
[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]

Swap rows and columns of the said array in reverse order:
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]
None


# Pandas Basics

In [ ]:
import pandas as pd

### Question 10 (5 points)
**Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.**
Sample Python dictionary data and list labels:
exam_data = {'name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Expected Output:
attempts name qualify score
a  A 1 yes 12.5
b  B no 3 9.0

------> Edit it to read it clearly

In [ ]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)

  name  score  attempts qualify
a    A   12.5         1     yes
b    B    9.0         3      no
c    C   16.5         2     yes
d    D    NaN         3      no
e    E    9.0         2      no
f    F   20.0         3     yes
g    G   14.5         1     yes
h    H    NaN         1      no
i    I    8.0         2      no
j    J   19.0         1     yes


### Question 11 (5 points)
**Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).**
Sample Python dictionary data and list labels:
exam_data = {'name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Expected Output:
Rows where score between 15 and 20 (inclusive):
attempts name qualify score
c 2 Katherine yes 16.5
f 3 Michael yes 20.0
j 1 Jonas yes 19.0.

------> Edit it to read it clearly

In [ ]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("Rows where score between 15 and 20 (inclusive):")
print(df[df['score'].between(15, 20)])


Rows where score between 15 and 20 (inclusive):
  name  score  attempts qualify
c    C   16.5         2     yes
f    F   20.0         3     yes
j    J   19.0         1     yes


### Question 12 (5 points)
**Write a Pandas program to add one row in an existing DataFrame.**
Sample data:
col1 col2 col3
0 1 4 7
1 4 5 8
2 3 6 9
3 4 7 0
4 5 8 1
After add one row:
col1 col2 col3
0 1 4 7
1 4 5 8
2 3 6 9
3 4 7 0
4 5 8 1
5 10 11 12

------> Edit it to read it clearly

In [ ]:
import pandas as pd
import numpy as np
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}
df = pd.DataFrame(data=d)
print(df)
print('After add one row:')
df2 = {'col1': 10, 'col2': 11, 'col3': 12}
df = df.append(df2, ignore_index=True)
print(df)


   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
After add one row:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12


### Question 13 (5 points)
**Write a Pandas program to get a list of a specified column of a DataFrame.**
Sample data:
col1 col2 col3
0 1 4 7
1 2 5 8
2 3 6 9
Col2 of the DataFrame to list:
[4, 5, 6]

------> Edit it to read it clearly

In [ ]:
import pandas as pd
d = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}
df = pd.DataFrame(data=d)
print(df)
col2_list = df["col2"].tolist()
print("Col2 of the DataFrame to list:")
print(col2_list)


   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
Col2 of the DataFrame to list:
[4, 5, 6]


### Question 14 (10 points)
**Write a Pandas program to find the particular row where the value of the  column is maximum.**
Sample Output:
  col1 col2 col3
0   1   11    7
1   2   12    8
2   3   13    12
3   4   14    1
4   5   10    11
Row where col1 has maximum value:
4
Row where col2 has maximum value:
3
Row where col3 has maximum value:
2

------> Edit it to read it clearly

In [ ]:
import pandas as pd
d = {'col1': [1, 2, 3, 4, 5], 'col2': [11, 12, 13, 14, 10], 'col3': [7, 8, 12, 1, 11]}
df = pd.DataFrame(data=d)
print(df)
print("Row where col1 has maximum value:")
print(df['col1'].argmax())
print("Row where col2 has maximum value:")
print(df['col2'].argmax())
print("Row where col3 has maximum value:")
print(df['col3'].argmax())


   col1  col2  col3
0     1    11     7
1     2    12     8
2     3    13    12
3     4    14     1
4     5    10    11
Row where col1 has maximum value:
4
Row where col2 has maximum value:
3
Row where col3 has maximum value:
2


### Question 15 (10 points)
**Create a DataFrame of your own choice which will have 5 columns with 10 rows filled by values**

1.   Show only first 5 values
2.   Show only last 5 values
3.   Show its info
4.   Show its columns






In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.info()

In [ ]:
df.column()