# Numpy

In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3,4])

In [3]:
np1

array([1, 2, 3, 4])

In [4]:
type(np1)

numpy.ndarray

In [5]:
Mat1 = np.array([[1,2],[3,4]])

In [6]:
Mat1

array([[1, 2],
       [3, 4]])

In [7]:
np1.shape

(4,)

In [8]:
Mat1.shape

(2, 2)

In [9]:
Mat1.dtype

dtype('int32')

In [10]:
Mat1[0,0] = 5

In [11]:
Mat1

array([[5, 2],
       [3, 4]])

In [12]:
Mat1[0,0] = "String"

ValueError: invalid literal for int() with base 10: 'String'

In [14]:
Mat2 = np.arange(0,10,1)

In [15]:
Mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
Mat3 = np.linspace(0,10,11)

In [19]:
Mat3

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
Mat4 = np.random.rand(5,5)

In [21]:
Mat4

array([[0.76159187, 0.69909543, 0.80870934, 0.38260558, 0.45120849],
       [0.19511725, 0.18248009, 0.19550401, 0.47967304, 0.65709741],
       [0.81126996, 0.42711458, 0.43231037, 0.16077445, 0.05037125],
       [0.89198121, 0.11803424, 0.69132134, 0.78182234, 0.0820433 ],
       [0.80753587, 0.91434046, 0.67390375, 0.33543302, 0.91627802]])

In [22]:
Mat5 = np.random.randn(5,5)

In [23]:
Mat5

array([[ 1.82060651,  0.91643691,  1.48806461, -0.61488401,  2.11684546],
       [ 0.30561336, -0.1451965 , -0.32674814,  0.2597334 ,  1.30661058],
       [-1.46810331,  0.51969738,  0.31445303,  0.49970747, -0.71492386],
       [-0.51345185, -0.20322258, -1.0522553 ,  0.87322688, -1.4724582 ],
       [ 0.3523559 ,  0.78159654, -0.21467635, -1.64930286,  0.78176946]])

- np.diag
- np.zeros
- np.ones

In [25]:
Mat5[0,0]

1.8206065100037674

In [26]:
Mat5[0.0] = 0

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [27]:
Mat5[0:3, :] # Excluding 3

array([[ 1.82060651,  0.91643691,  1.48806461, -0.61488401,  2.11684546],
       [ 0.30561336, -0.1451965 , -0.32674814,  0.2597334 ,  1.30661058],
       [-1.46810331,  0.51969738,  0.31445303,  0.49970747, -0.71492386]])